
import type { Tour, Category, Review, User, Booking } from "@/lib/types";

export const users: User[] = [
  {
    id: "user-1",
    name: "Alex Johnson",
    email: "alex@example.com",
    role: "user",
    profilePhoto: "https://placehold.co/100x100.png",
  },
  {
    id: "user-2",
    name: "Maria Garcia",
    email: "maria@example.com",
    role: "provider",
    profilePhoto: "https://placehold.co/100x100.png",
    isVerified: true,
  },
  {
    id: "user-3",
    name: "Admin User",
    email: "admin@tourvista.com",
    role: "admin",
    profilePhoto: "https://placehold.co/100x100.png",
  },
  {
    id: "user-4",
    name: "Jane Doe",
    email: "jane@example.com",
    role: "user",
    profilePhoto: "https://placehold.co/100x100.png",
  },
];

export const reviews: Review[] = [
  {
    id: "review-1",
    userId: "user-1",
    userName: "Alex Johnson",
    userImage: "https://placehold.co/100x100.png",
    rating: 5,
    comment: "Absolutely breathtaking! The guide was incredibly knowledgeable and friendly. A must-do tour in Tbilisi.",
    createdAt: "2023-10-15",
  },
  {
    id: "review-2",
    userId: "user-4",
    userName: "Jane Doe",
    userImage: "https://placehold.co/100x100.png",
    rating: 4,
    comment: "A wonderful day out. The scenery was amazing, though the lunch could have been better. Still highly recommend.",
    createdAt: "2023-10-12",
  },
];

export const tours: Tour[] = [
  {
    id: "1",
    title: "Old Tbilisi Walking Tour",
    location: "Tbilisi",
    category: "City Tours",
    price: 45,
    duration: "4 Hours",
    description: "Explore the historic heart of Georgia's capital. Wander through narrow, cobblestone streets, discover ancient churches, and marvel at the unique architecture of Old Tbilisi.",
    itinerary: [
      { title: "Metekhi Church", description: "Start with panoramic views of the old city." },
      { title: "Narikala Fortress", description: "Take a cable car up to the ancient fortress." },
      { title: "Abanotubani (Sulfur Baths)", description: "Visit the famous domed bathhouses." },
      { title: "Shardeni Street", description: "Explore the lively street with its many cafes and galleries." },
    ],
    images: [
      "https://placehold.co/800x600.png",
      "https://placehold.co/800x600.png",
      "https://placehold.co/800x600.png",
    ],
    providerId: "user-2",
    providerName: "Georgia Wonders",
    rating: 4.8,
    reviews: reviews,
    approved: true,
  },
  {
    id: "2",
    title: "Kazbegi Mountain Adventure",
    location: "Kazbegi",
    category: "Mountain & Hiking",
    price: 120,
    duration: "Full Day",
    description: "Journey along the stunning Georgian Military Highway to the majestic Kazbegi region. Witness the iconic Gergeti Trinity Church set against the backdrop of Mount Kazbek.",
     itinerary: [
      { title: "Ananuri Fortress", description: "Stop at the scenic castle complex on the Aragvi River." },
      { title: "Gudauri Viewpoint", description: "Admire the views from the Russia-Georgia Friendship Monument." },
      { title: "Gergeti Trinity Church", description: "Take a 4x4 drive up to the breathtakingly located church." },
    ],
    images: [
      "https://placehold.co/800x600.png",
      "https://placehold.co/800x600.png",
      "https://placehold.co/800x600.png",
    ],
    providerId: "user-2",
    providerName: "Georgia Wonders",
    rating: 4.9,
    reviews: [],
    approved: true,
  },
  {
    id: "3",
    title: "Kakheti Wine Region Tour",
    location: "Kakheti",
    category: "Wine & Gastronomy",
    price: 95,
    duration: "Full Day",
    description: "Discover the cradle of wine in the Kakheti region. Visit local wineries, taste unique Georgian wines made in qvevri, and enjoy the delicious local cuisine.",
     itinerary: [
      { title: "Bodbe Monastery", description: "Visit the beautiful monastery complex." },
      { title: "Sighnaghi", description: "Explore the charming 'City of Love' with its fortified walls." },
      { title: "Local Winery", description: "Enjoy a traditional wine tasting session and lunch." },
    ],
    images: [
      "https://placehold.co/800x600.png",
      "https://placehold.co/800x600.png",
    ],
    providerId: "user-2",
    providerName: "Georgia Wonders",
    rating: 4.7,
    reviews: [],
    approved: true,
  },
  {
    id: "4",
    title: "Uplistsikhe & Mtskheta Historical Tour",
    location: "Gori",
    category: "Historical & Cultural",
    price: 80,
    duration: "9 Hours",
    description: "Step back in time with a visit to the ancient cave city of Uplistsikhe and the former capital of Georgia, Mtskheta, a UNESCO World Heritage site.",
     itinerary: [
      { title: "Jvari Monastery", description: "Start with a view of the confluence of two rivers from this ancient monastery." },
      { title: "Svetitskhoveli Cathedral", description: "Explore the heart of the Georgian Orthodox church." },
      { title: "Uplistsikhe Cave Town", description: "Wander through the rock-hewn streets and structures." },
    ],
    images: [
      "https://placehold.co/800x600.png",
    ],
    providerId: "user-2",
    providerName: "Georgia Wonders",
    rating: 4.6,
    reviews: [],
    approved: false,
  },
  {
    id: "5",
    title: "Batumi City & Botanical Garden Tour",
    location: "Batumi",
    category: "City Tours",
    price: 60,
    duration: "6 Hours",
    description: "Explore the vibrant Black Sea city of Batumi, known for its modern architecture and lush greenery. Visit the world-renowned Batumi Botanical Garden.",
    itinerary: [
      { title: "Batumi Boulevard", description: "Stroll along the beautiful seaside park." },
      { title: "Ali and Nino Statue", description: "Witness the moving sculpture of eternal love." },
      { title: "Batumi Botanical Garden", description: "Explore one of the largest and most diverse botanical gardens." },
    ],
    images: [
      "https://placehold.co/800x600.png",
      "https://placehold.co/800x600.png",
    ],
    providerId: "user-2",
    providerName: "Georgia Wonders",
    rating: 4.8,
    reviews: [],
    approved: true,
  },
   {
    id: "6",
    title: "Svaneti UNESCO Heritage Expedition",
    location: "Svaneti",
    category: "Multi-Day Tours",
    price: 350,
    duration: "3 Days",
    description: "Embark on an unforgettable expedition to the remote and stunning region of Svaneti, famous for its medieval watchtowers and breathtaking Caucasus mountain landscapes.",
    itinerary: [
        { title: "Mestia", description: "Explore the administrative center of Svaneti and its unique watchtowers." },
        { title: "Ushguli", description: "Visit one of the highest continuously inhabited villages in Europe, a UNESCO site." },
        { title: "Chalaadi Glacier", description: "Hike to the foot of a stunning glacier." },
    ],
    images: [
      "https://placehold.co/800x600.png",
      "https://placehold.co/800x600.png",
      "https://placehold.co/800x600.png",
    ],
    providerId: "user-2",
    providerName: "Georgia Wonders",
    rating: 5.0,
    reviews: [],
    approved: true,
  }
];

export const categories: Category[] = [
  { id: "1", name: "City Tours" },
  { id: "2", name: "Mountain & Hiking" },
  { id: "3", name: "Wine & Gastronomy" },
  { id: "4", name: "Historical & Cultural" },
  { id: "5", name: "Multi-Day Tours" },
  { id: "6", name: "Adventure & Extreme" },
];


export const bookings: Booking[] = [
  {
    id: 'booking-1',
    userId: 'user-1',
    tourId: '1',
    tourTitle: 'Old Tbilisi Walking Tour',
    tourImage: 'https://placehold.co/800x600.png',
    bookingDate: '2023-11-20',
    guests: 2,
    totalPrice: 90,
    status: 'completed',
  },
  {
    id: 'booking-2',
    userId: 'user-1',
    tourId: '2',
    tourTitle: 'Kazbegi Mountain Adventure',
    tourImage: 'https://placehold.co/800x600.png',
    bookingDate: '2024-05-10',
    guests: 1,
    totalPrice: 120,
    status: 'confirmed',
  },
    {
    id: 'booking-3',
    userId: 'user-1',
    tourId: '3',
    tourTitle: 'Kakheti Wine Region Tour',
    tourImage: 'https://placehold.co/800x600.png',
    bookingDate: '2023-09-05',
    guests: 4,
    totalPrice: 380,
    status: 'cancelled',
  }
]
